Algoritmo "processamentoDeDados"

Var
    //Declarando duas variáveis do mesmo tipo na mesma linha
    //x, y : inteiro
    //x : real
    //y : inteiro
    
    b1, b2, h, area : real
Inicio
      //x <- 5.3
      //y <- Int(2 * x)
      //escreval("Valor de X: ", x)
      //escreval("Valor de Y: ", y)

      b1 <- 6.0
      b2 <- 8.0
      h <- 5.0
      
      area <- (b1 + b2)/2.0 * h
      
      escreval(area)
Fimalgoritmo