Algoritmo "estruturaVetor"

Var

    N, i : inteiro
    x : vetor [0..9] de real

Inicio

      escreva("Digite quantos casos irá inserir: ")
      leia(N)
      

      
      para i de 0 ate N-1 faca
           escreva("Digite um número: ")
           leia(x[i])
      fimpara
      
      escreval("Números digitados:")
      
      para i de 0 ate N-1 faca
           escreval(x[i])
      fimpara

Fimalgoritmo